sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mjcroc/docker-react-class-example -f Dockerfile.dev .

script:
  - docker run -e CI=true mjcroc/docker-react-class-example npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react-class-example'
  env: 'DockerReactClassExample-env'
  bucket_name: 'elasticbeanstalk-us-east-2-681776040209'
  bucket_path: 'docker-react-class-example'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
