sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mjcroc/docker-react-class-example -f Dockerfile.dev .

script:
  - docker run -e CI=true mjcroc/docker-react-class-example npm run test
